version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=hoge
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=sample
    volumes:
      - type: volume
        source: mysql
        target: /var/lib/mysql
    ports:
      - '13306:3306'

volumes:
  mysql:
